### ISSUE TITLE
Нужны мелкие правки

### ISSUE THREAD

**Issue by Mavlyan** [vivelekostas/SuperWorkOganizer#3]
1. папка DB_Lesson тебе больше не нужна. У тебя все примеры уже в основном коде есть.
Удали её плз в ближайшем комите

2. файл test.php лишний. Ну и заодном можно файл test2.php назвать по-человечески

3. файл TasksManager.php содержит закомментированный бесполезный код

**Comment by vivelekostas** [comment]
Готово шеф!
